url: https://localhost:7054
tls:
  enabled: true
  certfiles:
    - /home/siddharth/Downloads/Programming/fabric-assignment/network/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
  client:
    certfile: /home/siddharth/Downloads/Programming/fabric-assignment/network/crypto-config/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem
caname: ca-org1
csr:
  hosts:
    - localhost
    - ca.org1.example.com
